module.exports = {
  plugins: [
    "cleanupEnableBackground",
    "cleanupIds",
    "cleanupNumericValues",
    "collapseGroups",
    "convertColors",
    "convertEllipseToCircle",
    {
      name: "convertPathData",
      params: {
        removeUseless: false,
      },
    },
    "convertShapeToPath",
    "convertTransform",
    "inlineStyles",
    "mergePaths",
    "mergeStyles",
    "minifyStyles",
    "moveElemsAttrsToGroup",
    "moveGroupAttrsToElems",
    "removeComments",
    {
      name: "removeAttrs",
      params: {
        attrs: [
          "fill",
          "stroke",
          "stroke-linecap",
          "stroke-linejoin",
          "stroke-width",
          "style",
        ],
      },
    },
    "removeDesc",
    "removeDoctype",
    "removeEditorsNSData",
    "removeEmptyAttrs",
    "removeEmptyContainers",
    "removeEmptyText",
    "removeHiddenElems",
    "removeMetadata",
    "removeNonInheritableGroupAttrs",
    "removeOffCanvasPaths",
    "removeTitle",
    "removeUnknownsAndDefaults",
    "removeUnusedNS",
    "removeUselessDefs",
    "removeUselessStrokeAndFill",
    "removeXMLProcInst",
    {
      name: "sortAttrs",
      params: {
        order: ["xmlns", "width", "height", "viewBox"],
      },
    },
    "sortDefsChildren",
  ],
};
